apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config
  namespace: cloud-devops
  labels:
    app: fastapi-cloud-devops
    component: config
data:
  ENVIRONMENT: "production"
  PORT: "8000"
  LOG_LEVEL: "info"
  APP_VERSION: "1.0.0"
